### ISSUE TITLE
Doesn't work with non-ascii emails

### ISSUE THREAD

**Issue by gtd** [mspanc/rfc822#3]
I realize that RFC2822 does not support extended charsets and that that is pending RFC5335.  However the current situation leads to a huge gotcha where the documentation suggests matching against RFC822::EMAIL_REGEXP_WHOLE. However if this is done against a UTF-8 string with higher order chars then it pukes out a Encoding::CompatibilityError.  eg.

    "tóm@example.com" =~ RFC822::EMAIL_REGEXP_WHOLE

I realize you guard against this in the String methods, but the docs themselves list the direct match method.

**Comment by mspanc** [comment]
Thank you for your report. I will update the documentation and warn about this case.
